pipeline {
    agent any

    triggers {
        githubPush()
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/rishi539/devops.git'
            }
        }

        stage('Deploy to App Server') {
            steps {

                sh '''
                ssh -o StrictHostKeyChecking=no \
                -i ~/.ssh/devops-keypair.pem \
                ubuntu@10.0.130.255 << EOF

                cd /home/ubuntu/app/devops/NotesGen

                git pull origin main

                sudo docker compose down

                sudo docker compose up --build -d

                EOF
                '''
            }
        }
    }
}