pipeline {
    agent any

    triggers {
        githubPush()
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/rishi539/devops.git'
            }
        }

        stage('Connect to App Server') {
            steps {
                sh '''
ssh -o StrictHostKeyChecking=no \
-i /var/jenkins_home/.ssh/devops-keypair.pem \
ubuntu@10.0.130.255 "
echo Connected Successfully
"
'''
            }
        }

        stage('Pull Latest Code') {
            steps {
                sh '''
ssh -o StrictHostKeyChecking=no \
-i /var/jenkins_home/.ssh/devops-keypair.pem \
ubuntu@10.0.130.255 "
cd /home/ubuntu/app/devops/NotesGen

git reset --hard
git pull origin main
"
'''
            }
        }

        stage('Stop Containers') {
            steps {
                sh '''
ssh -o StrictHostKeyChecking=no \
-i /var/jenkins_home/.ssh/devops-keypair.pem \
ubuntu@10.0.130.255 "
cd /home/ubuntu/app/devops/NotesGen

sudo docker compose down
"
'''
            }
        }

        stage('Build and Start Containers') {
            steps {
                sh '''
ssh -o StrictHostKeyChecking=no \
-i /var/jenkins_home/.ssh/devops-keypair.pem \
ubuntu@10.0.130.255 "
cd /home/ubuntu/app/devops/NotesGen

sudo docker compose up --build -d
"
'''
            }
        }

        stage('Verify Running Containers') {
            steps {
                sh '''
ssh -o StrictHostKeyChecking=no \
-i /var/jenkins_home/.ssh/devops-keypair.pem \
ubuntu@10.0.130.255 "
sudo docker ps
"
'''
            }
        }
    }
}