spring:
  application:
    name: notes

  ai:
    ollama:

      base-url: https://9r7lkkln-11434.inc1.devtunnels.ms/

      # 🧠 Global default model (used for generic Ollama calls)
      model: gemma3:latest

      # 🎯 Chat-specific options (Spring AI ChatClient uses this)
      chat:
        options:
          model: gemma3:latest
          temperature: 0.3
          num-predict: 800

    google:
      genai:
        api-key: AIzaSyDBBtvJir4LJSxLPKaHHi-rEspJYAG-zDM
        chat:
          options:
            model: gemini-2.5-flash

  datasource:
    url: jdbc:mysql://localhost:3306/Notes
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
